export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN";
export const ADD_ITEM= "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const DECREASE_ITEM = "DECREASE_ITEM";
export const INCREASE_ITEM = "INCREASE_ITEM";

export const START_CLEAR_CART = "START_CLEAR_CART";
export const CLEAR_CART_SACCESS = "CLEAR_CART_SACCESS";
export const CLEAR_CART_FAILURE = "CLEAR_CART_FAILURE";

