export const UPDATE_COLLECTIONS = "UPDATE_COLLECTIONS";
export const START_FETCH_COLLECECTIONS = "START_FETCH_COLLECECTIONS";
export const FETCH_COLLECECTIONS_SUCCESS = "FETCH_COLLECECTIONS_SUCCESS";
export const FETCH_COLLECECTIONS_FAILURE = "FETCH_COLLECECTIONS_FAILURE";

