export const SET_CURRENT_USER = "SET_CURRENT_USER"

export const GOOGLE_SIGN_IN_START = "GOOGLE_SIGN_IN_START"
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS"
export const GOOGLE_SIGN_IN_FAILURE = "GOOGLE_SIGN_IN_FAILURE"

export const EMAIL_SIGN_IN_START = "EMAIL_SIGN_IN_START"
export const EMAIL_SIGN_IN_SUCCESS = "EMAIL_SIGN_IN_SUCCESS"
export const EMAIL_SIGN_IN_FAILURE = "EMAIL_SIGN_IN_FAILURE"

export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE"
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS"

export const START_SIGN_OUT = "START_SIGN_OUT"
export const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS"
export const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE"

export const START_SIGN_UP = "START_SIGN_UP"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE"






